# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw.xci
# IP: The module: 'axilite_clock_converter_32d32aw' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axilite_clock_converter_32d32aw'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axilite_clock_converter_32d32aw'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw.xci
# IP: The module: 'axilite_clock_converter_32d32aw' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axilite_clock_converter_32d32aw'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axilite_clock_converter_32d32aw'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
