# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW.xci
# IP: The module: 'axi_clock_converter_128D32AW' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_128D32AW'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_128D32AW'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW.xci
# IP: The module: 'axi_clock_converter_128D32AW' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_128D32AW'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_128D32AW'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
