# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
create_project -in_memory -part xcvu9p-flgb2104-2LV-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.cache/wt [current_project]
set_property parent.project_path /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/cn.vh
read_verilog -library xil_defaultlib -sv /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/xilinx_dma_pcie_ep.sv
read_verilog -library xil_defaultlib {
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/axi4_amm_slave.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/axi4_lite_amm_slave.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/cipherRound.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/cn_ml.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/cn_top.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/multi_core_top.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/random_math.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/uram_32768D128W.v
  /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/xdma_app.v
}
read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/mult_64wx64w_unsigned/mult_64wx64w_unsigned.xci
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/mult_64wx64w_unsigned/mult_64wx64w_unsigned_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/xdma_0.xci
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/xdma_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/source/xdma_0_pcie4_uscaleplus_ip.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/synth/xdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/xdma_0_pcie4_ip_board.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie4_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie4_ip_late.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/source/ip_pcie4_uscale_plus_x1y2.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie4_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie4_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_1/xdma_v4_1_3_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/xdma_0/ip_2/xdma_v4_1_3_blk_mem_64_noreg_be_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_amm_bridge/axi4_amm_bridge.xci
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_amm_bridge/axi4_amm_bridge.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_amm_bridge/axi4_amm_bridge_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xci
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi4_lite_amm_bridge/axi4_lite_amm_bridge_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW.xci
set_property used_in_synthesis false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axi_clock_converter_128D32AW/axi_clock_converter_128D32AW_ooc.xdc]

read_ip -quiet /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw.xci
set_property used_in_synthesis false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/xdma_0_ex.srcs/sources_1/ip/axilite_clock_converter_32d32aw/axilite_clock_converter_32d32aw_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/xilinx_pcie_xdma_ref_board.xdc
set_property used_in_implementation false [get_files /media/wanner/work/work/fpga_prj/Xmrig-fpga/xmrig_X1_brd/CNv4_top/imports/xilinx_pcie_xdma_ref_board.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_dma_pcie_ep -part xcvu9p-flgb2104-2LV-e -fanout_limit 128 -resource_sharing off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_dma_pcie_ep.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_dma_pcie_ep_utilization_synth.rpt -pb xilinx_dma_pcie_ep_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
